# -*- coding: utf-8 -*-
"""npl_spacy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kHtdivvPEiscNnTFN-ZeOHtodyGJSYWe
"""

!pip install -U spacy
!python -m spacy download es_core_news_md

import spacy
nlp = spacy.load('es_core_news_md')

sentence = nlp('La naturaleza es una fuente de inspiración, belleza y armonía. Nos ofrece paisajes maravillosos, recursos valiosos y lecciones de vida. Podemos disfrutar de la naturaleza de muchas formas: caminando por el bosque, observando las estrellas, escuchando el canto de los pájaros, respirando el aire puro, plantando un árbol, cuidando un animal, etc. La naturaleza nos brinda bienestar físico y mental, pero también nos exige respeto y responsabilidad. Debemos proteger la naturaleza de la contaminación, la deforestación, la extinción y el cambio climático. La naturaleza es nuestra casa común y debemos cuidarla como tal.')

def is_token_allowed(token: str) -> bool:
  return bool(
      token
      and not token.is_stop
      and token.is_alpha
      and not token.is_punct
  )

def preprocess_token(token: str) -> bool:
  return token.lemma_.strip().lower()

complete_filtered_tokens = [
  preprocess_token(token)
  for token in sentence
  if is_token_allowed(token)
]

complete_filtered_tokens