# -*- coding: utf-8 -*-
"""speech_recognition_assembly_ai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1agPCjQ9g2adT_Ab__44im_POQKq1MJYW

Libreria para extraer el audio de un video
"""

pip install moviepy pytube

"""Libreria para descargar videos de Youtube

Descargando el Video
"""

from pytube import YouTube

# Coloca aquí el enlace de YouTube
yt = YouTube('https://www.youtube.com/watch?v=Uj7Zo0U1FQQ')

# Selecciona el stream con solo audio
video = yt.streams.filter().first()

# Descarga el archivo de audio
url_video = video.download(filename='despacito.mp4')

"""Extrayendo el audio"""

from moviepy.editor import VideoFileClip

video = VideoFileClip(url_video)
audio = video.audio
audio.write_audiofile("audio_extraido.wav")

"""Configurando assemblyai, libreria que permite comunicarnos con los modelos de Assembly Ai"""

# `pip3 install assemblyai` (macOS)
# `pip install assemblyai` (Windows)

import assemblyai as aai

api_key = "87c399be6b6e4a7a976d5079a536e934"
upload_endpoint = 'https://api.assemblyai.com/v2/upload'
transcript_endpoint = 'https://api.assemblyai.com/v2/transcript'
filename = "audio_extraido.wav"

headers_auth_only = {'authorization': api_key}

headers = {
    "authorization": api_key,
    "content-type": "application/json"
}

CHUNK_SIZE = 5_242_880  # 5MB

"""Realizando la transcripción"""

import assemblyai as aai

aai.settings.api_key = api_key

transcriber = aai.Transcriber()

audio_url = (
    filename
)

config = aai.TranscriptionConfig(language_code="es")

transcript = transcriber.transcribe(audio_url, config)

print(transcript.text)