# -*- coding: utf-8 -*-
"""translation_with_Helsinki_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MrdKpYqfxOKpjqIE8XFLWHKYfSJ8TG5F
"""

import pandas as pd
from pandas import DataFrame
from transformers import pipeline

translator = pipeline("translation", model="Helsinki-NLP/opus-mt-tc-big-en-es")

def translate(text: str) -> str:
  return translator(text)[0]['translation_text']

def translate_df_to_spanish(df: DataFrame, columns: list[str]) -> DataFrame:
  df_copy = df.copy()
  df_copy[columns] = df_copy[columns].applymap(
    lambda value: translate(value)
  )
  return df_copy


def translate_df_to_spanish_with_counter(df: DataFrame, columns: list[str]) -> DataFrame:
  df_copy = df.copy()
  for i, row in df_copy.iterrows():
    print(f"Procesando la fila {i+1}")
    for column in columns:
      text_translated = translate(str(row[column]))
      df_copy.at[i, column] = text_translated
  return df_copy

translate('hello, good morning')