# -*- coding: utf-8 -*-
"""speech_recognition_whisper_empingao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q4OcG_-5L2SCV5wfgyIJEpi8s-bKKvr6
"""

!pip install -U openai-whisper
!pip install --upgrade --no-deps --force-reinstall git+https://github.com/openai/whisper.git
!pip install setuptools-rust
!pip install moviepy pytube

# on Ubuntu or Debian
!sudo apt update && sudo apt install ffmpeg

# on Arch Linux
!sudo pacman -S ffmpeg

# on MacOS using Homebrew (https://brew.sh/)
!brew install ffmpeg

# on Windows using Chocolatey (https://chocolatey.org/)
!choco install ffmpeg

# on Windows using Scoop (https://scoop.sh/)
!scoop install ffmpeg

from pytube import YouTube

video_url = 'https://www.youtube.com/watch?v=kJQP7kiw5Fk'
audio_output = 'audio.wav'

# Coloca aquí el enlace de YouTube
yt = YouTube(video_url)

# Selecciona el stream con solo audio
audio = yt.streams.get_audio_only()

# Descarga el archivo de audio
audio.download(filename=audio_output)

from IPython.display import Audio
Audio(audio_output)

from moviepy.editor import VideoFileClip

video = VideoFileClip("despacito.mp4")
audio = video.audio
audio.write_audiofile(audio_output)

import whisper

model = whisper.load_model("base")
result = model.transcribe("audio_extraido.wav", language='spanish', fp16=False)
print(result["text"])