# -*- coding: utf-8 -*-
"""ETL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zDPCk0J4X9VcbVpinZwqNe6fHK_oQnDD
"""

import pandas as pd
from pandas import DataFrame

"""Limpiar el texto con spacy"""

def get_columns(df: DataFrame) -> list:
  return df.columns.tolist()


def extract_csv(path: str) -> DataFrame:
  df = pd.read_csv(path)
  return df


def load_csv(path: str, df: DataFrame) -> None:
  df.to_csv(path, index=False)


def transform_optimized(df: DataFrame, columns: list[str]) -> DataFrame:
    # Realiza las modificaciones en las columnas especificadas
    df[columns] = df[columns].applymap(
      lambda value: ' '.join([
        preprocess_token(token)
        for token in nlp(value)
        if is_token_allowed(token)
      ]))

    # Devuelve el DataFrame modificado
    return df.copy()

# df = extract_csv('netflix_titles.csv')
# transform(df)
# load_csv('nuevo_datasset.csv', df)
df = extract_csv('netflix_titles.csv')
columns = get_columns(df)
df_sp = transform_optimized(df, columns)
load_csv('netflix_titles_clean.csv', df_sp)